version: "3.8"

services: 
  db: 
    image: "mysql:8.0"
    volumes:
      - "dbapp:/var/lib/mysql"
    environment: 
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - 127.0.0.1:3307:3306
    networks:
      - symfony_db_net

  nginx: 
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    ports:
      - 80:80
    volumes:
      - ./apps/my-symfony-app/:/var/www/app
    networks:
      - symfony_db_net

  php: 
    build : 
      context: .
      dockerfile: docker/php/Dockerfile
    volumes:
      - ./apps/my-symfony-app/:/var/www/app
    expose: 
      - 9000
    networks:
      - symfony_db_net
      
volumes:
    dbapp:
networks:
    symfony_db_net:


